import type { Income, Expense, Asset, Debt, Project } from "@/types";

// Henderson family: Jake + Sarah
// Combined monthly income target: $13,750
//   Jake salary:      $7,500/mo  ($90k/yr)
//   Sarah salary:     $5,200/mo  ($62.4k/yr)
//   Sarah consulting: $800/mo
//   Dividends:        $250/mo
//   Jake bonus:       $8,000/yr  (~$667/mo)
// Total monthly: $14,417 (incl. bonus amortized)

export const mockIncomes: Income[] = [
  {
    id: "inc-1",
    name: "Jake Salary — Senior Product Manager",
    amount: 7_500,
    frequency: "monthly",
    category: "salary",
    owner: "Jake",
    isActive: true,
    startDate: "2020-04-01",
    notes: "Net after 401(k) pre-tax deduction",
  },
  {
    id: "inc-2",
    name: "Sarah Salary — Registered Nurse",
    amount: 5_200,
    frequency: "monthly",
    category: "salary",
    owner: "Sarah",
    isActive: true,
    startDate: "2018-09-10",
  },
  {
    id: "inc-3",
    name: "Sarah Consulting — Healthcare Staffing",
    amount: 800,
    frequency: "monthly",
    category: "freelance",
    owner: "Sarah",
    isActive: true,
    notes: "Per-diem shifts; varies $400–$1,200",
  },
  {
    id: "inc-4",
    name: "Investment Dividends",
    amount: 250,
    frequency: "monthly",
    category: "investment",
    owner: "Joint",
    isActive: true,
    notes: "Brokerage + dividend ETFs",
  },
  {
    id: "inc-5",
    name: "Jake Annual Performance Bonus",
    amount: 8_000,
    frequency: "annually",
    category: "salary",
    owner: "Jake",
    isActive: true,
    notes: "Paid in March; ~10% of base",
  },
];

// Monthly expense target: ~$12,500
// Housing $3,600 | Food $1,400 | Transport $1,050
// Kids $900 | Health $720 | Insurance $540
// Entertainment $380 | Personal $310 | Pets $200
// Savings/Retirement $1,900 | Utilities $380 | Other $320 = $11,700 fixed
// Remainder is variable flex

export const mockExpenses: Expense[] = [
  // ── Housing ────────────────────────────────────────────────
  {
    id: "exp-1",
    name: "Mortgage Payment",
    amount: 2_650,
    frequency: "monthly",
    category: "housing",
    isFixed: true,
    isEssential: true,
    notes: "30yr fixed @ 7.125% — 218 Birchwood Ln",
  },
  {
    id: "exp-2",
    name: "HOA Fees",
    amount: 210,
    frequency: "monthly",
    category: "housing",
    isFixed: true,
    isEssential: true,
  },
  {
    id: "exp-3",
    name: "Property Taxes",
    amount: 5_400,
    frequency: "annually",
    category: "housing",
    isFixed: true,
    isEssential: true,
  },
  {
    id: "exp-4",
    name: "Home Maintenance",
    amount: 290,
    frequency: "monthly",
    category: "housing",
    isFixed: false,
    isEssential: true,
    notes: "1% rule annualized + misc repairs",
  },

  // ── Utilities ──────────────────────────────────────────────
  {
    id: "exp-5",
    name: "Electricity",
    amount: 145,
    frequency: "monthly",
    category: "utilities",
    isFixed: false,
    isEssential: true,
  },
  {
    id: "exp-6",
    name: "Natural Gas",
    amount: 68,
    frequency: "monthly",
    category: "utilities",
    isFixed: false,
    isEssential: true,
  },
  {
    id: "exp-7",
    name: "Water & Sewer",
    amount: 58,
    frequency: "monthly",
    category: "utilities",
    isFixed: false,
    isEssential: true,
  },
  {
    id: "exp-8",
    name: "Internet — Xfinity",
    amount: 79,
    frequency: "monthly",
    category: "utilities",
    isFixed: true,
    isEssential: true,
  },
  {
    id: "exp-9",
    name: "Phone Plans (2 lines)",
    amount: 110,
    frequency: "monthly",
    category: "utilities",
    isFixed: true,
    isEssential: true,
  },

  // ── Food ───────────────────────────────────────────────────
  {
    id: "exp-10",
    name: "Groceries",
    amount: 980,
    frequency: "monthly",
    category: "food",
    isFixed: false,
    isEssential: true,
    notes: "Family of 4 + meal prep",
  },
  {
    id: "exp-11",
    name: "Dining Out",
    amount: 420,
    frequency: "monthly",
    category: "food",
    isFixed: false,
    isEssential: false,
  },

  // ── Transport ──────────────────────────────────────────────
  {
    id: "exp-12",
    name: "Jake Car Payment — Honda Accord",
    amount: 485,
    frequency: "monthly",
    category: "transport",
    isFixed: true,
    isEssential: true,
    notes: "2023 Honda Accord Sport — 60mo @ 6.4%",
  },
  {
    id: "exp-13",
    name: "Gas & Fuel",
    amount: 220,
    frequency: "monthly",
    category: "transport",
    isFixed: false,
    isEssential: true,
  },
  {
    id: "exp-14",
    name: "Auto Insurance (2 vehicles)",
    amount: 2_760,
    frequency: "annually",
    category: "insurance",
    isFixed: true,
    isEssential: true,
    notes: "6-mo policy; Progressive",
  },
  {
    id: "exp-15",
    name: "Vehicle Registration & Fees",
    amount: 480,
    frequency: "annually",
    category: "transport",
    isFixed: true,
    isEssential: true,
  },

  // ── Kids ───────────────────────────────────────────────────
  {
    id: "exp-16",
    name: "Daycare — Lily (age 3)",
    amount: 1_380,
    frequency: "monthly",
    category: "education",
    isFixed: true,
    isEssential: true,
    notes: "Full-time daycare center",
  },
  {
    id: "exp-17",
    name: "After-school / Activities — Owen (age 7)",
    amount: 310,
    frequency: "monthly",
    category: "education",
    isFixed: false,
    isEssential: true,
    notes: "Soccer + piano lessons",
  },
  {
    id: "exp-18",
    name: "School Supplies & Clothing — Kids",
    amount: 120,
    frequency: "monthly",
    category: "education",
    isFixed: false,
    isEssential: true,
  },
  {
    id: "exp-19",
    name: "529 Contributions — Owen & Lily",
    amount: 300,
    frequency: "monthly",
    category: "savings",
    isFixed: true,
    isEssential: true,
    notes: "$150 each child",
  },

  // ── Health ─────────────────────────────────────────────────
  {
    id: "exp-20",
    name: "Health Insurance Premium (family)",
    amount: 510,
    frequency: "monthly",
    category: "healthcare",
    isFixed: true,
    isEssential: true,
    notes: "Jake employer plan — BCBS family PPO",
  },
  {
    id: "exp-21",
    name: "Dental & Vision Insurance",
    amount: 72,
    frequency: "monthly",
    category: "healthcare",
    isFixed: true,
    isEssential: true,
  },
  {
    id: "exp-22",
    name: "Medical Copays & Prescriptions",
    amount: 138,
    frequency: "monthly",
    category: "healthcare",
    isFixed: false,
    isEssential: true,
  },

  // ── Insurance ──────────────────────────────────────────────
  {
    id: "exp-23",
    name: "Homeowner's Insurance",
    amount: 1_680,
    frequency: "annually",
    category: "insurance",
    isFixed: true,
    isEssential: true,
  },
  {
    id: "exp-24",
    name: "Term Life Insurance (Jake)",
    amount: 480,
    frequency: "annually",
    category: "insurance",
    isFixed: true,
    isEssential: true,
    notes: "20yr $750k policy — Haven Life",
  },
  {
    id: "exp-25",
    name: "Term Life Insurance (Sarah)",
    amount: 360,
    frequency: "annually",
    category: "insurance",
    isFixed: true,
    isEssential: true,
    notes: "20yr $500k policy",
  },
  {
    id: "exp-26",
    name: "Umbrella Policy",
    amount: 240,
    frequency: "annually",
    category: "insurance",
    isFixed: true,
    isEssential: true,
    notes: "$1M liability umbrella",
  },

  // ── Retirement / Savings ───────────────────────────────────
  {
    id: "exp-27",
    name: "Jake 401(k) Contribution",
    amount: 750,
    frequency: "monthly",
    category: "savings",
    isFixed: true,
    isEssential: true,
    notes: "Pre-tax; employer matches 4%",
  },
  {
    id: "exp-28",
    name: "Sarah Roth IRA",
    amount: 583,
    frequency: "monthly",
    category: "savings",
    isFixed: true,
    isEssential: true,
    notes: "$7k/yr max contribution",
  },
  {
    id: "exp-29",
    name: "Emergency Fund Savings",
    amount: 400,
    frequency: "monthly",
    category: "savings",
    isFixed: true,
    isEssential: true,
    notes: "HYSA — building to 6 months",
  },

  // ── Entertainment ──────────────────────────────────────────
  {
    id: "exp-30",
    name: "Netflix",
    amount: 22.99,
    frequency: "monthly",
    category: "entertainment",
    isFixed: true,
    isEssential: false,
  },
  {
    id: "exp-31",
    name: "Spotify Family",
    amount: 16.99,
    frequency: "monthly",
    category: "entertainment",
    isFixed: true,
    isEssential: false,
  },
  {
    id: "exp-32",
    name: "Disney+",
    amount: 13.99,
    frequency: "monthly",
    category: "entertainment",
    isFixed: true,
    isEssential: false,
  },
  {
    id: "exp-33",
    name: "Family Outings & Events",
    amount: 250,
    frequency: "monthly",
    category: "entertainment",
    isFixed: false,
    isEssential: false,
    notes: "Movies, parks, weekend trips",
  },
  {
    id: "exp-34",
    name: "Jake Gym — Planet Fitness",
    amount: 25,
    frequency: "monthly",
    category: "entertainment",
    isFixed: true,
    isEssential: false,
  },

  // ── Personal ───────────────────────────────────────────────
  {
    id: "exp-35",
    name: "Clothing — Adults",
    amount: 130,
    frequency: "monthly",
    category: "personal",
    isFixed: false,
    isEssential: false,
  },
  {
    id: "exp-36",
    name: "Personal Care & Hair",
    amount: 95,
    frequency: "monthly",
    category: "personal",
    isFixed: false,
    isEssential: false,
  },
  {
    id: "exp-37",
    name: "Jake Amazon / Misc Shopping",
    amount: 85,
    frequency: "monthly",
    category: "personal",
    isFixed: false,
    isEssential: false,
  },

  // ── Pets ───────────────────────────────────────────────────
  {
    id: "exp-38",
    name: "Dog Food & Supplies — Biscuit",
    amount: 95,
    frequency: "monthly",
    category: "personal",
    isFixed: false,
    isEssential: true,
    notes: "Golden Retriever",
  },
  {
    id: "exp-39",
    name: "Vet & Pet Insurance — Biscuit",
    amount: 105,
    frequency: "monthly",
    category: "healthcare",
    isFixed: false,
    isEssential: true,
  },

  // ── Debt payments ──────────────────────────────────────────
  {
    id: "exp-40",
    name: "Student Loan — Sarah",
    amount: 298,
    frequency: "monthly",
    category: "debt",
    isFixed: true,
    isEssential: true,
    notes: "Federal — income-driven repayment",
  },
];

export const mockAssets: Asset[] = [
  {
    id: "ast-1",
    name: "Primary Residence — 218 Birchwood Ln",
    value: 520_000,
    category: "real_estate",
    appreciationRate: 4.5,
    purchasePrice: 430_000,
    purchaseDate: "2021-08-20",
  },
  {
    id: "ast-2",
    name: "Jake 401(k) — Fidelity",
    value: 98_400,
    category: "retirement",
    appreciationRate: 7.0,
  },
  {
    id: "ast-3",
    name: "Sarah Roth IRA — Vanguard",
    value: 42_600,
    category: "retirement",
    appreciationRate: 7.0,
  },
  {
    id: "ast-4",
    name: "Joint Brokerage — Fidelity",
    value: 31_200,
    category: "investment",
    appreciationRate: 8.0,
    notes: "FZROX + dividend ETFs",
  },
  {
    id: "ast-5",
    name: "High-Yield Savings — SoFi",
    value: 19_400,
    category: "cash",
    notes: "Emergency fund — 4.6% APY",
  },
  {
    id: "ast-6",
    name: "Joint Checking — Chase",
    value: 7_800,
    category: "cash",
  },
  {
    id: "ast-7",
    name: "2023 Honda Accord Sport",
    value: 28_500,
    category: "vehicle",
    purchasePrice: 34_200,
    purchaseDate: "2023-01-15",
    appreciationRate: -12,
  },
  {
    id: "ast-8",
    name: "2020 Toyota RAV4",
    value: 22_100,
    category: "vehicle",
    purchasePrice: 31_500,
    purchaseDate: "2020-03-08",
    appreciationRate: -12,
  },
  {
    id: "ast-9",
    name: "529 Plan — Owen",
    value: 12_800,
    category: "investment",
    appreciationRate: 6.5,
  },
  {
    id: "ast-10",
    name: "529 Plan — Lily",
    value: 5_400,
    category: "investment",
    appreciationRate: 6.5,
  },
];

export const mockDebts: Debt[] = [
  {
    id: "dbt-1",
    name: "Mortgage — 218 Birchwood Ln",
    balance: 388_200,
    originalBalance: 430_000,
    interestRate: 7.125,
    minimumPayment: 2_650,
    category: "mortgage",
    lender: "US Bank",
    notes: "30yr fixed, originated Aug 2021",
  },
  {
    id: "dbt-2",
    name: "Auto Loan — Honda Accord",
    balance: 22_400,
    originalBalance: 30_000,
    interestRate: 6.4,
    minimumPayment: 485,
    category: "auto",
    lender: "Honda Financial Services",
  },
  {
    id: "dbt-3",
    name: "Student Loan — Sarah (Federal)",
    balance: 19_800,
    originalBalance: 32_000,
    interestRate: 4.99,
    minimumPayment: 298,
    category: "student",
    lender: "MOHELA",
    notes: "Income-driven repayment plan",
  },
  {
    id: "dbt-4",
    name: "Chase Sapphire Preferred",
    balance: 1_640,
    originalBalance: 1_640,
    interestRate: 22.99,
    minimumPayment: 35,
    category: "credit_card",
    lender: "Chase",
    notes: "Paid in full each month — current balance",
  },
];

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    name: "Backyard Deck & Patio",
    description: "Cedar deck + stamped concrete patio with pergola",
    totalBudget: 22_000,
    amountSpent: 7_800,
    category: "home_improvement",
    status: "in_progress",
    targetDate: "2026-09-15",
    expenses: [
      { id: "pe-1", name: "Design & permits", amount: 1_400, isPaid: true },
      { id: "pe-2", name: "Materials deposit", amount: 6_400, isPaid: true },
      { id: "pe-3", name: "Concrete & labor", amount: 7_200, isPaid: false },
      { id: "pe-4", name: "Pergola kit", amount: 3_800, isPaid: false },
      { id: "pe-5", name: "Landscaping & lighting", amount: 3_200, isPaid: false },
    ],
  },
  {
    id: "proj-2",
    name: "Family Vacation — Pacific Northwest",
    description: "8-day road trip: Portland → Olympic NP → Seattle",
    totalBudget: 7_500,
    amountSpent: 1_200,
    category: "vacation",
    status: "in_progress",
    targetDate: "2026-08-01",
    expenses: [
      { id: "pe-6", name: "Hotel bookings", amount: 1_200, isPaid: true },
      { id: "pe-7", name: "National Park passes", amount: 120, isPaid: false },
      { id: "pe-8", name: "Gas & rental car", amount: 980, isPaid: false },
      { id: "pe-9", name: "Food & dining", amount: 1_600, isPaid: false },
      { id: "pe-10", name: "Activities & tours", amount: 1_400, isPaid: false },
      { id: "pe-11", name: "Misc & souvenirs", amount: 500, isPaid: false },
    ],
  },
  {
    id: "proj-3",
    name: "Emergency Fund — 6-Month Goal",
    description: "Build HYSA to $25,000 (6 months of core expenses)",
    totalBudget: 25_000,
    amountSpent: 19_400,
    category: "emergency_fund",
    status: "in_progress",
    expenses: [],
    notes: "Currently at $19,400 — $5,600 remaining at $400/mo",
  },
  {
    id: "proj-4",
    name: "New Roof",
    description: "Replace 18-yr-old asphalt shingle roof",
    totalBudget: 14_000,
    amountSpent: 0,
    category: "home_improvement",
    status: "planned",
    targetDate: "2027-05-01",
    expenses: [],
    notes: "3 quotes received: $12,800 – $15,400",
  },
];
